/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AbmEdicion.java
 *
 * Created on 20-ago-2011, 11:31:57
 */
package vista;

import java.awt.Component;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import javax.swing.text.MaskFormatter;
import negocio.ControlAula;
import negocio.ControlCurso;
import negocio.ControlDia;
import negocio.ControlEdicion;
import negocio.ControlEmpleado;

/**
 *
 * @author oscarribera
 */
public class AbmEdicion extends javax.swing.JPanel {

    private ModeloTabla modeloEdiciones = new ModeloTabla(new String[]{"id", "curso", "docente", "aula", "fechaInicio", "fechaFin"});
    private DefaultListModel modeloDiasClase = new DefaultListModel();
    private ControlEdicion controlEdicion = new ControlEdicion();

    /** Creates new form AbmEdicion */
    public AbmEdicion() {
        initComponents();
        init();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JFormattedTextField();
        try {
            MaskFormatter formatter = new MaskFormatter("##-####");
            this.txtId = new JFormattedTextField(formatter);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        dateInicio = new com.toedter.calendar.JDateChooser();
        dateFin = new com.toedter.calendar.JDateChooser();
        comboDocentes = new javax.swing.JComboBox();
        comboAulas = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        listDiasClase = new javax.swing.JList();
        comboDias = new javax.swing.JComboBox();
        btnAddDia = new javax.swing.JButton();
        btnDelDia = new javax.swing.JButton();
        comboCursos = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEdiciones = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Campos"));

        jLabel1.setText("ID:");

        jLabel2.setText("Fecha inicio:");

        jLabel3.setText("Fecha fin:");

        jLabel4.setText("Docente:");

        jLabel5.setText("Curso:");

        jLabel6.setText("Aula:");

        jLabel7.setText("Dias de clase:");

        comboDocentes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboAulas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        listDiasClase.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listDiasClase);

        comboDias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAddDia.setText("Agregar");
        btnAddDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDiaActionPerformed(evt);
            }
        });

        btnDelDia.setText("Quitar");
        btnDelDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelDiaActionPerformed(evt);
            }
        });

        comboCursos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel7)
                    .add(jLabel2)
                    .add(jLabel1)
                    .add(jLabel5)
                    .add(jLabel4)
                    .add(jLabel6)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(comboDias, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, btnDelDia, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, btnAddDia, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .add(txtId, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .add(dateInicio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .add(dateFin, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .add(comboCursos, 0, 264, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, comboDocentes, 0, 264, Short.MAX_VALUE)
                    .add(comboAulas, 0, 264, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtId, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel3)
                                .add(22, 22, 22))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                .add(dateInicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(dateFin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(14, 14, 14))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(92, Short.MAX_VALUE)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(comboCursos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel5))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(comboDocentes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(comboAulas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .add(12, 12, 12)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel7)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(comboDias, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnAddDia)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(btnDelDia)))
                .addContainerGap())
        );

        tablaEdiciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaEdiciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEdicionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEdiciones);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar);

        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar);

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void btnAddDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDiaActionPerformed
    addDiaClase();

}//GEN-LAST:event_btnAddDiaActionPerformed

private void btnDelDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelDiaActionPerformed
    delDiaClase();

}//GEN-LAST:event_btnDelDiaActionPerformed

private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
    nuevo();
}//GEN-LAST:event_btnNuevoActionPerformed

private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
    agregar();
}//GEN-LAST:event_btnAgregarActionPerformed

private void tablaEdicionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEdicionesMouseClicked
    select();
}//GEN-LAST:event_tablaEdicionesMouseClicked

private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
    modificar();
}//GEN-LAST:event_btnModificarActionPerformed

private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    eliminar();
}//GEN-LAST:event_btnEliminarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDia;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnDelDia;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox comboAulas;
    private javax.swing.JComboBox comboCursos;
    private javax.swing.JComboBox comboDias;
    private javax.swing.JComboBox comboDocentes;
    private com.toedter.calendar.JDateChooser dateFin;
    private com.toedter.calendar.JDateChooser dateInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listDiasClase;
    private javax.swing.JTable tablaEdiciones;
    private javax.swing.JFormattedTextField txtId;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.tablaEdiciones.setModel(modeloEdiciones);
        this.listDiasClase.setModel(modeloDiasClase);
        this.comboDocentes.setRenderer(new DocenteComboRenderer());
        cargarDatos();
        cargarCombos();
    }

    private void cargarDatos() {
        this.modeloEdiciones.setDatos(controlEdicion.getEdiciones());
    }

    private void cargarCombos() {
        ControlAula controlAula = new ControlAula();
        ControlDia controlDia = new ControlDia();
        ControlCurso controlCurso = new ControlCurso();


        this.comboAulas.removeAllItems();
        for (Object[] item : controlAula.getAulas()) {
            this.comboAulas.addItem(item[0]);
        }
        //
        this.comboDias.removeAllItems();
        for (Object[] item : controlDia.getDias()) {
            this.comboDias.addItem(item[0]);
        }
        //
        this.comboCursos.removeAllItems();
        for (Object[] item : controlCurso.getCursos()) {
            this.comboCursos.addItem(item[0]);
        }
        loadComboDocentes();
    }

    private void loadComboDocentes() {
        this.comboDocentes.removeAllItems();
        String edicion = this.txtId.getText();
        for (Object[] item : controlEdicion.getDocentes(edicion)) {
            this.comboDocentes.addItem(item);
        }
    }

    private void addDiaClase() {
        Object dia = comboDias.getSelectedItem();
        if (!modeloDiasClase.contains(dia)) {
            modeloDiasClase.addElement(dia);
        }
    }

    private void delDiaClase() {
        Object dia = listDiasClase.getSelectedValue();
        if (dia != null) {
            modeloDiasClase.removeElement(dia);
        }
    }

    private void nuevo() {
        enableModificar(false);
        txtId.setEditable(true);
        this.txtId.setText("");
        this.dateInicio.setDate(new Date());
        this.dateFin.setDate(new Date());
        this.modeloDiasClase.clear();
    }

    private void enableModificar(boolean enable) {
        this.btnAgregar.setEnabled(!enable);
        this.btnModificar.setEnabled(enable);
        this.btnEliminar.setEnabled(enable);
    }

    private void agregar() {
        if (txtId.getText().isEmpty() || dateFin.getDate().before(dateInicio.getDate()) || modeloDiasClase.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Datos invalidos");
        } else {
            Object[] docente = (Object[]) comboDocentes.getSelectedItem();
            Integer docenteId = (Integer) docente[0];
            String cursoId = comboCursos.getSelectedItem().toString();
            String aulaId = comboAulas.getSelectedItem().toString();
            Object[] diasClase = modeloDiasClase.toArray();
            String resultado = controlEdicion.addEdicion(this.txtId.getText(), cursoId, docenteId, aulaId, dateInicio.getDate(), dateFin.getDate(), diasClase);
            cargarDatos();
            JOptionPane.showMessageDialog(this, resultado);
        }
    }

    private void select() {
        int index = tablaEdiciones.getSelectedRow();
        if (index > -1) {
            enableModificar(true);
            txtId.setEditable(false);
            txtId.setText(modeloEdiciones.getValueAt(index, 0).toString());
            dateInicio.setDate((Date) modeloEdiciones.getValueAt(index, 4));
            dateFin.setDate((Date) modeloEdiciones.getValueAt(index, 5));
            comboCursos.setSelectedItem(modeloEdiciones.getValueAt(index, 1));
            comboAulas.setSelectedItem(modeloEdiciones.getValueAt(index, 3));
            loadComboDocentes();
            loadDiasClase(modeloEdiciones.getValueAt(index, 0).toString());
        }
    }

    private void loadDiasClase(String edicion) {
        modeloDiasClase.clear();
        for (Object[] item : controlEdicion.getDiasClase(edicion)) {
            modeloDiasClase.addElement(item[0]);
        }
    }

    private void modificar() {
        if (dateFin.getDate().before(dateInicio.getDate()) || modeloDiasClase.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Datos invalidos");
        } else {
            Object[] docente = (Object[]) comboDocentes.getSelectedItem();
            Integer docenteId = (Integer) docente[0];
            String cursoId = comboCursos.getSelectedItem().toString();
            String aulaId = comboAulas.getSelectedItem().toString();
            Object[] diasClase = modeloDiasClase.toArray();
            String resultado = controlEdicion.modificarEdicion(this.txtId.getText(), cursoId, docenteId, aulaId, dateInicio.getDate(), dateFin.getDate(), diasClase);
            cargarDatos();
            JOptionPane.showMessageDialog(this, resultado);
        }
    }

    private void eliminar() {
        String resultado = controlEdicion.delEdicion(this.txtId.getText());
        cargarDatos();
        JOptionPane.showMessageDialog(this, resultado);
    }

    private class DocenteComboRenderer extends JLabel implements ListCellRenderer {

        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {

            if (isSelected) {
                setBackground(list.getSelectionBackground());
                setForeground(list.getSelectionForeground());
            } else {
                setBackground(list.getBackground());
                setForeground(list.getForeground());
            }
            Object[] selected = (Object[]) value;
            setText(selected[1].toString());
            return this;
        }
    }
}
